/** 
 * This file was generated by 'vite-plugin-kit-routes'
 * 
 *      >> DO NOT EDIT THIS FILE MANUALLY <<
 */

export const PAGES = {
  "/": `/`,
  "/admin": `/admin`,
  "/admin/conferences": `/admin/conferences`,
  "/admin/thumbnails": `/admin/thumbnails`,
  "/admin/thumbnails/[id]": (params: {id: (string | number)}) =>  {
        return `/admin/thumbnails/${params.id}`
      },
  "/[year]/[season]": (params: {year: (string | number), season: (string | number)}) =>  {
        return `/${params.year}/${params.season}`
      },
  "/[year]/[season]/[slug]": (params: {year: (string | number), season: (string | number), slug: (string | number)}) =>  {
        return `/${params.year}/${params.season}/${params.slug}`
      },
  "/[year]/[season]/signup": (params: {year: (string | number), season: (string | number)}) =>  {
        return `/${params.year}/${params.season}/signup`
      },
  "/[year]/[season]/sponsors": (params: {year: (string | number), season: (string | number)}) =>  {
        return `/${params.year}/${params.season}/sponsors`
      },
  "/[year]/[season]/submit": (params: {year: (string | number), season: (string | number)}) =>  {
        return `/${params.year}/${params.season}/submit`
      },
  "/email-confirmed": `/email-confirmed`
}

export const SERVERS = {
  "/api/login/redirect/[service]/[...redirect]": (method: 'GET', params: {service: (string | number), redirect: (string | number)[]}) =>  {
        return `/api/login/redirect/${params.service}/${params.redirect?.join('/')}`
      },
  "/api/satori/[id].png": (method: 'prerender' | 'entries' | 'GET', params: {id: (string | number)}) =>  {
        return `/api/satori/${params.id}.png`
      },
  "/api/verify-email/[hash]": (method: 'GET', params: {hash: (string | number)}) =>  {
        return `/api/verify-email/${params.hash}`
      },
  "/sitemap.xml": (method: 'prerender' | 'GET') =>  {
        return `/sitemap.xml`
      }
}

export const ACTIONS = {
  "/[year]/[season]/signup": (action: 'subscribe', params: {year: (string | number), season: (string | number)}) =>  {
        return `/${params.year}/${params.season}/signup?/${action}`
      }
}

export const LINKS = {
  
}

const appendSp = (sp?: Record<string, string | number | undefined>, prefix: '?' | '&' = '?') => {
  if (sp === undefined) return ''
  const mapping = Object.entries(sp)
    .filter(c => c[1] !== undefined)
    .map(c => [c[0], String(c[1])])

  const formated = new URLSearchParams(mapping).toString()
  if (formated) {
    return `${prefix}${formated}`
  }
  return ''
}


/**
* Add this type as a generic of the vite plugin `kitRoutes<KIT_ROUTES>`.
* 
* Full example:
* ```ts
* import type { KIT_ROUTES } from './ROUTES'
* import { kitRoutes } from 'vite-plugin-kit-routes'
* 
* kitRoutes<KIT_ROUTES>({
*  PAGES: {
*    // here, "paths" it will be typed!
*  }
* })
* ```
*/
export type KIT_ROUTES = { 
  PAGES: { '/': never, '/admin': never, '/admin/conferences': never, '/admin/thumbnails': never, '/admin/thumbnails/[id]': 'id', '/[year]/[season]': 'year' | 'season', '/[year]/[season]/[slug]': 'year' | 'season' | 'slug', '/[year]/[season]/signup': 'year' | 'season', '/[year]/[season]/sponsors': 'year' | 'season', '/[year]/[season]/submit': 'year' | 'season', '/email-confirmed': never }
  SERVERS: { '/api/login/redirect/[service]/[...redirect]': 'service' | 'redirect', '/api/satori/[id].png': 'id', '/api/verify-email/[hash]': 'hash', '/sitemap.xml': never }
  ACTIONS: { '/[year]/[season]/signup': 'year' | 'season' }
  LINKS: {  }
  Params: { id: never, year: never, season: never, slug: never, service: never, redirect: never, hash: never }
}
